// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    var image, images, newNode, _i, _len, _results;
    images = document.querySelectorAll(".artThumb");
    _results = [];
    for (_i = 0, _len = images.length; _i < _len; _i++) {
      image = images[_i];
      newNode = document.createElement("img");
      image.onmouseover = function() {
        var oldsrc, parts;
        newNode = document.createElement('img');
        oldsrc = this.src;
        parts = oldsrc.split('/');
        newNode.src = "images/art/" + parts[parts.length - 1];
        newNode.style = 'border:solid 1px black;';
        newNode.className = 'bigImg';
        this.parentNode.appendChild(newNode);
        return console.log(this.src);
      };
      _results.push(image.onmouseout = function() {
        var _j, _len1, _results1;
        images = document.querySelectorAll(".bigImg");
        _results1 = [];
        for (_j = 0, _len1 = images.length; _j < _len1; _j++) {
          image = images[_j];
          _results1.push(image.parentNode.removeChild(image));
        }
        return _results1;
      });
    }
    return _results;
  };

}).call(this);
